### ISSUE TITLE
error in the validation loop of train.py

### ISSUE THREAD

**Issue by raotnameh** [raotnameh/Robust_ASR#1]
@iamjanvijay  I'm getting this error when running train.py

File "train.py", line 443, in <module>
    class_wise_precision, class_wise_recall, class_wise_f1 = tps/(tps+fps), tps/(fns+fps), 2 * class_wise_precision * class_wise_recall / (class_wise_precision + class_wise_recall)
NameError: name 'class_wise_precision' is not defined

**Comment by iamjanvijay** [comment]
Have made appropriate changes. Please close the issue.
